import "server-only";
import { createCipheriv, createDecipheriv, createHmac, randomBytes, timingSafeEqual } from "node:crypto";

export type GoogleTokens={access_token:string;refresh_token?:string;expires_at:number;scope?:string};
export type SearchRow={keys:string[];clicks:number;impressions:number;ctr:number;position:number};
const appUrl=()=>process.env.NEXT_PUBLIC_APP_URL?.replace(/\/$/,"")||"http://localhost:3000";
const secret=()=>{const value=process.env.CONNECTOR_ENCRYPTION_KEY;if(!value)throw new Error("CONNECTOR_ENCRYPTION_KEY is not configured.");const key=Buffer.from(value,"base64");if(key.length!==32)throw new Error("CONNECTOR_ENCRYPTION_KEY must be a 32-byte base64 value.");return key};
export const gscConfigured=()=>Boolean(process.env.GOOGLE_CLIENT_ID&&process.env.GOOGLE_CLIENT_SECRET&&process.env.CONNECTOR_ENCRYPTION_KEY);
export const redirectUri=()=>`${appUrl()}/api/connectors/gsc/callback`;

export function createOAuthState(userId:string){const nonce=randomBytes(16).toString("hex");const payload=Buffer.from(JSON.stringify({userId,nonce,expires:Date.now()+10*60_000})).toString("base64url");const signature=createHmac("sha256",secret()).update(payload).digest("base64url");return `${payload}.${signature}`}
export function verifyOAuthState(state:string){const [payload,signature]=state.split(".");if(!payload||!signature)throw new Error("Invalid OAuth state.");const expected=createHmac("sha256",secret()).update(payload).digest();const received=Buffer.from(signature,"base64url");if(expected.length!==received.length||!timingSafeEqual(expected,received))throw new Error("Invalid OAuth state.");const data=JSON.parse(Buffer.from(payload,"base64url").toString()) as {userId:string;expires:number};if(data.expires<Date.now())throw new Error("OAuth request expired.");return data}
export function encryptTokens(tokens:GoogleTokens){const iv=randomBytes(12);const cipher=createCipheriv("aes-256-gcm",secret(),iv);const encrypted=Buffer.concat([cipher.update(JSON.stringify(tokens),"utf8"),cipher.final()]);return {v:1,iv:iv.toString("base64"),tag:cipher.getAuthTag().toString("base64"),data:encrypted.toString("base64")}}
export function decryptTokens(value:unknown){const item=value as {iv:string;tag:string;data:string};const decipher=createDecipheriv("aes-256-gcm",secret(),Buffer.from(item.iv,"base64"));decipher.setAuthTag(Buffer.from(item.tag,"base64"));return JSON.parse(Buffer.concat([decipher.update(Buffer.from(item.data,"base64")),decipher.final()]).toString()) as GoogleTokens}

export function authorizationUrl(state:string){const q=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID!,redirect_uri:redirectUri(),response_type:"code",scope:"https://www.googleapis.com/auth/webmasters.readonly",access_type:"offline",prompt:"consent",include_granted_scopes:"true",state});return `https://accounts.google.com/o/oauth2/v2/auth?${q}`}
export async function exchangeCode(code:string):Promise<GoogleTokens>{const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({code,client_id:process.env.GOOGLE_CLIENT_ID!,client_secret:process.env.GOOGLE_CLIENT_SECRET!,redirect_uri:redirectUri(),grant_type:"authorization_code"}),cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error_description||"Google authorization failed.");return {...data,expires_at:Date.now()+data.expires_in*1000}}
export async function validAccessToken(tokens:GoogleTokens){if(tokens.expires_at>Date.now()+60_000)return tokens; if(!tokens.refresh_token)throw new Error("Google connection expired. Reconnect Search Console.");const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID!,client_secret:process.env.GOOGLE_CLIENT_SECRET!,refresh_token:tokens.refresh_token,grant_type:"refresh_token"}),cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error("Could not refresh Google access.");return {...tokens,access_token:data.access_token,expires_at:Date.now()+data.expires_in*1000}}
async function google<T>(url:string,accessToken:string,init?:RequestInit){const response=await fetch(url,{...init,headers:{authorization:`Bearer ${accessToken}`,"content-type":"application/json",...init?.headers},cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error?.message||"Google Search Console request failed.");return data as T}
export async function listSites(accessToken:string){const data=await google<{siteEntry?:{siteUrl:string;permissionLevel:string}[]}>("https://www.googleapis.com/webmasters/v3/sites",accessToken);return data.siteEntry??[]}
export async function searchAnalytics(accessToken:string,siteUrl:string,dimensions:("query"|"page")[]){const end=new Date();const start=new Date(end);start.setDate(start.getDate()-27);const date=(d:Date)=>d.toISOString().slice(0,10);const data=await google<{rows?:SearchRow[]}>(`https://www.googleapis.com/webmasters/v3/sites/${encodeURIComponent(siteUrl)}/searchAnalytics/query`,accessToken,{method:"POST",body:JSON.stringify({startDate:date(start),endDate:date(end),dimensions,rowLimit:10})});return data.rows??[]}

