import "server-only";
import { createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import type { GoogleTokens } from "./google-search-console";

const appUrl=()=>process.env.NEXT_PUBLIC_APP_URL?.replace(/\/$/,"")||"http://localhost:3000";
const key=()=>{const value=process.env.CONNECTOR_ENCRYPTION_KEY;if(!value)throw new Error("CONNECTOR_ENCRYPTION_KEY is not configured.");return Buffer.from(value,"base64")};
export const gbpConfigured=()=>Boolean(process.env.GOOGLE_CLIENT_ID&&process.env.GOOGLE_CLIENT_SECRET&&process.env.CONNECTOR_ENCRYPTION_KEY);
export const gbpRedirectUri=()=>`${appUrl()}/api/connectors/google-business-profile/callback`;
export function createGbpState(userId:string){const payload=Buffer.from(JSON.stringify({userId,nonce:randomBytes(16).toString("hex"),expires:Date.now()+10*60_000})).toString("base64url");const sig=createHmac("sha256",key()).update(`gbp:${payload}`).digest("base64url");return `${payload}.${sig}`}
export function verifyGbpState(state:string){const [payload,sig]=state.split(".");if(!payload||!sig)throw new Error("Invalid Google Business Profile state.");const expected=createHmac("sha256",key()).update(`gbp:${payload}`).digest();const received=Buffer.from(sig,"base64url");if(expected.length!==received.length||!timingSafeEqual(expected,received))throw new Error("Invalid Google Business Profile state.");const data=JSON.parse(Buffer.from(payload,"base64url").toString()) as {userId:string;expires:number};if(data.expires<Date.now())throw new Error("Google authorization expired.");return data}
export function gbpAuthorizationUrl(state:string){const q=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID!,redirect_uri:gbpRedirectUri(),response_type:"code",scope:"https://www.googleapis.com/auth/business.manage",access_type:"offline",prompt:"consent",state});return `https://accounts.google.com/o/oauth2/v2/auth?${q}`}
export async function exchangeGbpCode(code:string):Promise<GoogleTokens>{const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({code,client_id:process.env.GOOGLE_CLIENT_ID!,client_secret:process.env.GOOGLE_CLIENT_SECRET!,redirect_uri:gbpRedirectUri(),grant_type:"authorization_code"}),cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error_description||"Google Business Profile authorization failed.");return {...data,expires_at:Date.now()+data.expires_in*1000}}
async function google<T>(url:string,token:string){const response=await fetch(url,{headers:{authorization:`Bearer ${token}`},cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error?.message||"Google Business Profile API request failed.");return data as T}
export async function listGbpLocations(token:string){const accounts=(await google<{accounts?:{name:string;accountName?:string}[]}>("https://mybusinessaccountmanagement.googleapis.com/v1/accounts",token)).accounts??[];const locations=[] as {resourceName:string;title:string}[];for(const account of accounts){const data=await google<{locations?:{name:string;title?:string}[]}>(`https://mybusinessbusinessinformation.googleapis.com/v1/${account.name}/locations?readMask=name,title`,token);for(const location of data.locations??[])locations.push({resourceName:`${account.name}/${location.name}`,title:location.title||account.accountName||location.name})}return locations}
export async function publishGbpPost(token:string,location:string,summary:string,imageUrl?:string){const response=await fetch(`https://mybusiness.googleapis.com/v4/${location}/localPosts`,{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({languageCode:"en-US",summary,topicType:"STANDARD",...(imageUrl?{media:[{mediaFormat:"PHOTO",sourceUrl:imageUrl}]}:{})}),cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error?.message||"Google Business Profile publishing failed.");return String(data.name||"")}

