import { createClient } from "@/lib/supabase/server";
import { addAudit, runAutomatedAudit } from "./actions";
import { comparisonScore, type Audit } from "@/lib/audits";
import type { SeoScan } from "@/lib/seo-scanner";

type Run = Audit & { technical_score:number|null; content_score:number|null; performance_score:number|null; issues_count:number; summary:string|null; details:SeoScan|Record<string,never> };

export default async function Audits({searchParams}:{searchParams:Promise<{message?:string;error?:string}>}) {
  const params=await searchParams; const s=await createClient();
  const [{data:websites=[]},{data:raw=[]}]=await Promise.all([s.from("websites").select("id,name,url"),s.from("audit_runs").select("id,website_id,score,technical_score,content_score,performance_score,issues_count,summary,details,created_at,websites(name)").order("created_at",{ascending:false})]);
  const audits=(raw??[]) as unknown as Run[]; const latest=audits[0];
  return <><h1>SEO Audit history</h1><p className="muted">Scan a public website automatically and track improvement at 30/90/180/365-day checkpoints.</p>
    {params.message&&<p className="notice">{params.message}</p>}{params.error&&<p className="alert">{params.error}</p>}
    <div className="grid section">{[30,90,180,365].map(d=>{const old=comparisonScore(audits,d);return <div className="card" key={d}><span className="muted">vs {d} days</span><div className="metric">{old===null?"â€”":`${(latest?.score??0)-old>=0?"+":""}${(latest?.score??0)-old}`}</div></div>})}</div>
    <div className="grid two section"><div className="card"><h2>Automated scan</h2>{!websites?.length?<p className="alert">Add a website first.</p>:<form action={runAutomatedAudit} className="form"><label>Website<select name="website_id">{websites.map(w=><option key={w.id} value={w.id}>{w.name} â€” {w.url}</option>)}</select></label><p className="muted small">Checks on-page SEO, crawl files, HTTPS and response time. The scan can take up to 15 seconds.</p><button className="btn">Run SEO scan</button></form>}</div>
      <div className="card"><h2>Latest automated result</h2>{!latest?<div className="empty">No audit runs yet.</div>:<><div className="score-row"><div><span className="muted">Overall</span><div className="metric">{latest.score}/100</div></div><div><span className="muted">Issues</span><div className="metric">{latest.issues_count}</div></div></div><p>{latest.summary}</p>{"checks" in (latest.details??{})&&<div className="checks">{(latest.details as SeoScan).checks.map(c=><div className="check" key={c.key}><span className={`badge ${c.passed?"good":"bad"}`}>{c.passed?"Pass":"Fix"}</span><span><strong>{c.label}</strong><br/><span className="muted small">{c.detail}</span></span></div>)}</div>}</>}</div></div>
    <div className="grid two section"><div className="card"><h2>Manual record</h2>{!websites?.length?<p className="alert">Add a website first.</p>:<form action={addAudit} className="form"><label>Website<select name="website_id">{websites.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><div className="form-row"><label>Overall score<input name="score" type="number" min="0" max="100" required /></label><label>Issues<input name="issues_count" type="number" min="0" required /></label></div><div className="form-row"><label>Technical<input name="technical_score" type="number" min="0" max="100" required /></label><label>Content<input name="content_score" type="number" min="0" max="100" required /></label></div><label>Performance<input name="performance_score" type="number" min="0" max="100" required /></label><label>Summary<textarea name="summary" rows={3}/></label><button className="btn secondary">Save manual audit</button></form>}</div>
      <div className="card"><h2>Runs</h2>{!audits.length?<div className="empty">No audit runs yet.</div>:<table><thead><tr><th>Website</th><th>Score</th><th>Issues</th><th>Date</th></tr></thead><tbody>{audits.map(a=><tr key={a.id}><td>{a.websites?.name??"Website"}</td><td><span className="badge good">{a.score}/100</span></td><td>{a.issues_count}</td><td>{new Date(a.created_at).toLocaleDateString()}</td></tr>)}</tbody></table>}</div></div></>;
}

